spring:
  application:
    name: bookapi

  datasource:
    url: jdbc:mysql://localhost:3306/catalogoLivros?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: test

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
